version: '3.3'
services:
  dev:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'dev'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sei'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
